### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by gfrivolt** [rcs/jsenv-brunch#12]
I'm getting this error on `npm i jsenv-brunch`

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "i" "jsenv-brunch@1.4.2"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path /Users/fifigyuri/Projects/environet3x/ui/node_modules/jsenv-brunch
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/Users/fifigyuri/Projects/environet3x/ui/node_modules/jsenv-brunch' -> '/Users/fifigyuri/Projects/environet3x/ui/node_modules/.jsenv-brunch.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fifigyuri/Projects/environet3x/ui/npm-debug.log
```

The same happens on `npm i jsenv-brunch@1.4.2` or `npm i git+https://github.com/rcs/jsenv-brunch.git`.

I'm using node v6.5.0 and npm v3.10.3. Thanks for help.

**Comment by mattdodge** [comment]
Looks like something is in `node_modules/jsenv-brunch` already? Try `rm -rf /Users/fifigyuri/Projects/environet3x/ui/node_modules/jsenv-brunch` and then reinstall. If that doesn't work you can always go to the trusty `rm -rf node_modules && npm install` - that tends to fix problems more often than it should.

**Comment by iStefo** [comment]
I have the same issue within an Elixir Phoenix project when using brunch@2.8.2 and jsenv-brunch@2.0.0 in **`devDependencies`**. Moving `jsenv-brunch` to **`dependencies`** solved the problem.

**Comment by kyliepedersen** [comment]
I was having the same issue and ran `rm -rf node_modules` and then installed jsenv-brunch on it's own: `npm install jsenv-brunch` and then ran `npm install` to install the other needed dependencies. Not sure why jsenv-brunch was having issues when trying to install everything at once, but it solved the problem.

**Comment by gfrivolt** [comment]
`rm -rf node_modules` helped as it often does with `npm`. Thank you! Closing, I don't think there is any issue with the plugin itself
